# Generated by Django 4.0.1 on 2022-01-20 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.BooleanField()),
                ('content', models.CharField(max_length=500)),
                ('hwp', models.CharField(max_length=100)),
                ('hwp_progress', models.CharField(blank=True, choices=[('미착수', '미착수'), ('진행중', '진행중'), ('완료', '완료')], max_length=100)),
                ('pdf', models.CharField(max_length=100)),
                ('pdf_progress', models.CharField(blank=True, choices=[('미착수', '미착수'), ('진행중', '진행중'), ('완료', '완료')], max_length=100)),
                ('script', models.CharField(max_length=100)),
                ('script_progress', models.CharField(blank=True, choices=[('미착수', '미착수'), ('진행중', '진행중'), ('완료', '완료')], max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
