# Generated by Django 4.0.1 on 2022-01-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('sq', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('pwd', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('gubun', models.CharField(choices=[('공급기업', '공급기업'), ('수요기업', '수요기업')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
